### PR TITLE
Update to net5

### PR DESCRIPTION
**Pull request by paulovila**

### CODE REVIEW

**Comment by paulovila** [comment]
I'm not an expert in F#, for some reason the code is not traversing recursively through the dependencies, do you have any idea?

**Comment by cezarypiatek** [comment]
Thanks!

**Comment by paulovila** [comment]
Hi @cezarypiatek , this change still doesn't work properly, for some reason it is not traversing recursively through the dependencies, do you have any idea?

**Comment by cezarypiatek** [comment]
This project was created 7 years ago as an exercise.  To be honest, I don't need it now for any purpose. If you have any benefits of it, feel free to investigate the issue, I'm open to merge your PR.

**Pull request merged**
